
package com.allegro.webapi;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "serviceService", targetNamespace = "https://webapi.allegro.pl/service.php", wsdlLocation = "https://webapi.allegro.pl/service.php?wsdl")
public class ServiceService
    extends Service
{

    private final static URL SERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.allegro.webapi.ServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.allegro.webapi.ServiceService.class.getResource(".");
            url = new URL(baseUrl, "https://webapi.allegro.pl/service.php?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://webapi.allegro.pl/service.php?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICESERVICE_WSDL_LOCATION = url;
    }

    public ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceService() {
        super(SERVICESERVICE_WSDL_LOCATION, new QName("https://webapi.allegro.pl/service.php", "serviceService"));
    }

    /**
     * 
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "servicePort")
    public ServicePort getServicePort() {
        return super.getPort(new QName("https://webapi.allegro.pl/service.php", "servicePort"), ServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "servicePort")
    public ServicePort getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://webapi.allegro.pl/service.php", "servicePort"), ServicePort.class, features);
    }

}
